### ISSUE TITLE
CsrfGuard.isAjaxRequest() misidentify non-ajax request as true?

### ISSUE THREAD

**Issue by stalinone** [aramrami/OWASP-CSRFGuard#1]
In [CsrfGuard.java](https://github.com/aramrami/OWASP-CSRFGuard-3/blob/08e19cf39570d03275b280be72a027f1983a486f/csrfguard/src/main/java/org/owasp/csrfguard/CsrfGuard.java#L533-L535), it identify ajax request as if `X-Requested-With` is set:

```java
	private boolean isAjaxRequest(HttpServletRequest request) {
		return request.getHeader("X-Requested-With") != null;
	}
```

However, Android stock browser sends `X-Requested-With: com.android.browser` with any requests, even non-ajax ones. This would lead any regular and legit GET/POST requests being misidentified as [invalid](https://github.com/aramrami/OWASP-CSRFGuard-3/blob/08e19cf39570d03275b280be72a027f1983a486f/csrfguard/src/main/java/org/owasp/csrfguard/CsrfGuard.java#L310-L311).

**Affected:** Android 4+ stock browser maybe? I reproduce the problem on 4.3 and 4.4.2 via GenyMotion emulator.

**Longer description**: I use whitelist protection (`org.owasp.csrfguard.Protect=true`) and set Ajax support on (`org.owasp.csrfguard.Ajax=true`). When using Android stock browser, CsrfGuard would misidentify my GET/POST action as an CSRF attack and logged `required token is missing from the request`. I checked that the token is set in POST data and query string, and if I set Ajax support off then the request will successfully submitted.

**Comment by aramrami** [comment]
Is it possible to post a Pull Request to include the solution in the repository.
Thanks

**Comment by ilsurih** [comment]
@aramrami, why did this issue closed?

**Comment by aramrami** [comment]
I don't close it.

Azzedine RAMRAMI
