### ISSUE TITLE
CSRF Token are not getting attached to the request, while accessing the server on IPV6

### ISSUE THREAD

**Issue by futtu** [aramrami/OWASP-CSRFGuard#100]
private String parseDomain(StringBuffer url) of 
org.owasp/csrfguard/3.0.0/org/owasp/csrfguard/servlet/JavaScriptServlet.java 
file is parsing the url assuming its a IPV4 address.
Returning the wrong domain if IPV6 address comes in the URL

**Comment by glitchcube** [comment]
That is a good point, @futtu. @aramrami I have created a pull-request to try to fix this issue.

**Comment by aramrami** [comment]
Let me take a look and I will merge the request.

**Comment by aramrami** [comment]
I merged one and closed an other. Can you submit the missing one?

**Comment by samtribs** [comment]
I am getting this error method:POST, uri:/login/sessionInfo.json, error:required token is missing from the request 
in GWT. I am not sure why it is blocking POST request
