### ISSUE TITLE
 [Owasp-csrfguard] CSRFGuard 3.1 - unexpected token in csrfguard.js

### ISSUE THREAD

**Issue by rachn** [aramrami/OWASP-CSRFGuard#101]
I am trying to add CSRFGuard for our website. I managed to configure CSRFGuard and I see the token in my pages but there is an error in the JavaScript: 
 
function isValidDomain(current, target) {
                           var result = false;
                           
                           /** check exact or subdomain match **/
                           if(current == target) {
                                        result = true;
                           } else if( %DOMAIN_STRICT% == false) {
                                        if(target.charAt(0) == '.') {
                                                     result = current.endsWith(target);
                                        } else {
                                                     result = current.endsWith('.' + target);
                                        }
                                        
                           }
                           
                           return result;
             }
 
 
This happens for all the attributes of the JavaScriptServlet with % tag. Please help.
 
Best Regards,
Rachna Jain

**Comment by aramrami** [comment]
If you can code the solution and create a pull request. I will merge it after.
