### ISSUE TITLE
CSRFGuard 3.1 -- Refresh button doesn't work

### ISSUE THREAD

**Issue by rachn** [aramrami/OWASP-CSRFGuard#102]
Hi,

I implemented CSRFGuard on my website withthe following settings in crfguard.properties:

org.owasp.csrfguard.JavascriptServlet.injectIntoForms = true
org.owasp.csrfguard.JavascriptServlet.injectFormAttributes = true
org.owasp.csrfguard.JavascriptServlet.injectIntoAttributes = true 
org.owasp.csrfguard.TokenPerPage=false
org.owasp.csrfguard.TokenPerPagePrecreate=false
org.owasp.csrfguard.Rotate=true
org.owasp.csrfguard.Ajax=true
org.owasp.csrfguard.JavascriptServlet.domainStrict = true
org.owasp.csrfguard.JavascriptServlet.cacheControl = private, maxage=28800
org.owasp.csrfguard.JavascriptServlet.refererMatchDomain = false
org.owasp.csrfguard.JavascriptServlet.refererPattern = .*
org.owasp.csrfguard.TokenLength=32
org.owasp.csrfguard.SessionKey=OWASP_CSRFTOKEN
org.owasp.csrfguard.TokenName=OWASP-CSRFTOKEN
org.owasp.csrfguard.PRNG=SHA1PRNG

The website works alright as I can see the token for the Post requests. Back/Forward button work fine too. But the refresh button doesn't work. It detects as CSRF attack. Please help.

**Comment by aramrami** [comment]
I did suceeed to reproduce this issue. What solution did you try?

**Comment by forgedhallpass** [comment]
In the meantime the code-base has been heavily reworked, improved and extended with new functionalities. The new release candidate version can be found on the official repository under [releases](https://github.com/OWASP/www-project-csrfguard/releases).

Please feel free to try it out and provide your feedback.

**Comment by forgedhallpass** [comment]
@rachn since we haven't heard back from you, this issue will be closed. If you have any further problems, please open a ticket on the official repository at https://github.com/OWASP/www-project-csrfguard
