### ISSUE TITLE
CSRFGuard Overlay file uses a hardcoded overlay name

### ISSUE THREAD

**Issue by Restlessjoker** [aramrami/OWASP-CSRFGuard#104]
The ConfigurationOverlayProvider uses a hardcoded value to determine overlay files.

public static final String OWASP_CSRF_GUARD_OVERLAY_PROPERTIES = "Owasp.CsrfGuard.overlay.properties";

A suggestion would be to allow this to be overridden (Like the default configuration file)
Example below:

    <context-param>
        <param-name>Owasp.CsrfGuard.Config</param-name>
        <param-value>Owasp.CsrfGuard.custom.name.properties</param-value>
    </context-param>

**Comment by aramrami** [comment]
If you can code the solution and create a pull request. I will merge it after.
