### ISSUE TITLE
Adding support for Fetch API similar to the XMLHttpRequest

### ISSUE THREAD

**Issue by bronogard** [aramrami/OWASP-CSRFGuard#105]
The following support was added for `XMLHttpRequest` - extracted from https://github.com/aramrami/OWASP-CSRFGuard/blob/master/csrfguard/src/main/resources/csrfguard.js#L472:

```
XMLHttpRequest.prototype.onsend = function(data) {
				if(isValidUrl(this.url)) {
					this.setRequestHeader("X-Requested-With", "XMLHttpRequest")
					this.setRequestHeader(token_name, token_value);
				}
			};
```

**Comment by glitchcube** [comment]
Is this an issue that should be open?

**Comment by alexsheppard11** [comment]
Currently CSRFGuard only supports xhr requests, it would be good for it to support fetch too.

**Comment by glitchcube** [comment]
Not so familiar with the fetch api, but I can see that older browser is not supporting this API. Particularly IE does not support it at all. One could consider using the new fetch API, just be aware of supporting browser.

If this is the end will result in having both XHR and fetch to support all browsers. Then I think we should stick to XHR. 

Anyone got more to add to this topic?

**Comment by aramrami** [comment]
If you can code a solution and create a pull request. I will merge it after.
