### ISSUE TITLE
[Struts + CSRFGuard 3.1] OWASP_TOKEN doesn't get embedded to the HTTP header

### ISSUE THREAD

**Issue by susenj** [aramrami/OWASP-CSRFGuard#106]
WebServer: Tomcat 8
OS: Linux (CentOs 7 - 64bit)
Browsers: Chrome/Firefox latest

Experts, I have followed the OWASP CSRFguard wiki and its test project to include it for my application that has a mix of **struts 1.1 and struts 2.5** webpages. I was successfully able to get the **JavaScriptServlet** generate the OWASP_TOKEN for the first time on the landing page.
The moment, I navigate to any other page/link in the application, it lands to the error.html page citing "missing required token".

What I have tried and got no luck with:

1. Kept all pages as protected.
2. Made all useless items unprotected, for example, .js, .css etc.
3. Embedded the JavaScriptServlet inside every .jsp file.
4. Researched almost all related articles on internet and tried all related suggestions.
5. Took packet captures over each try and see token not getting injected after it's created.

Now, I have begun to think that it's probably the csrfguard which is not supported in Struts. Source: https://lists.owasp.org/pipermail/owasp-csrfguard/2015-August/000335

Could someone confirm or deny this? I am totally out of clues now. 

Thanks

**Comment by glitchcube** [comment]
Could you have a look to see if your pages can access the JavascriptServlet?
When I tried on my own project there were a couple of issues I stumbled on. 
The primary problem was that the pages couldn’t locate the servlet. 

Try using absolute path to see if that works.

**Comment by susenj** [comment]
Thanks @glitchcube for responding. The JavaScriptServlet we could see on the first landing page only and other pages don't have it. We tried with the absolute path as well, but that didn't help.  Do you have an example of how to use absolute path, perhaps we might be doing something wrong we don't know?

-susenj

**Comment by glitchcube** [comment]
Hi,

Can you share how you provide link to the JavaScriptServlet?
An absolute path would looks like this. "http://localhost:8080/applicationRoot/JavaScriptServlet".
A relative path would look like this "/JavascriptServlet". The problem I had with the last solution was when I had pages that was not at the same level as the JavascriptServlet. 

If we have two pages were both have an relative link to the servlet "/JavaScriptServlet":
page1: http://localhost:8080/applicationRoot/page1.html
page2: http://localhost:8080/applicationRoot/pages/page2.html

When the browser looks for the Servlet they would look at the following location
page1: http://localhost:8080/applicationRoot/JavaScriptServlet
page2: http://localhost:8080/applicationRoot/pages/JavaScriptServlet.

This was the reason I had problem finding the servlet at page2.
The way I have solved it is to let the servletcontainer resolve the absolute path dynamically: 
`<script type="text/javascript" src="#{request.contextPath}/JavaScriptServlet"></script>`

Just post back if you still have problem. Hope we can resolve this issue.

- Frank

**Comment by aramrami** [comment]
If you can code the solution and create a pull request. I will merge it after.
