### ISSUE TITLE
CSRF Overlay File expects a hardcoded filepath

### ISSUE THREAD

**Issue by Restlessjoker** [aramrami/OWASP-CSRFGuard#107]
In the csrf.properties file, when using a file outside of the classpath to override the properties, the filepath cannot be made relative at all. It is consumed as is.

org.owasp.csrfguard.configOverlay.hierarchy = classpath:Owasp.CsrfGuard.properties, classpath:Owasp.CsrfGuard.overlay.properties, file:<filepath>/Overlay.overlay

What would be nice is if, when using an external csrf properties file, we could leverage a java system property (Ideally with a configurable name) to set a root path to the file.

For example

org.owasp.csrfguard.configOverlay.hierarchy = classpath:Owasp.CsrfGuard.properties, classpath:Owasp.CsrfGuard.overlay.properties, file:<my_root_configuration_path_java_property>/security/csrfguard/Overlay.overlay

**Comment by aramrami** [comment]
Please propose a solution and create a pull request and I will merge it
