### ISSUE TITLE
Page not validated if TokenPerPage is True but Protect is False

### ISSUE THREAD

**Issue by tsenovIvan** [aramrami/OWASP-CSRFGuard#108]
Hello,

Documentation states that CSRFGuard by default validates all but explicitly declared as unprotected pages. This behavior is reversed by setting org.owasp.csrfguard.Protect to True.

With pull request #97, this was added to verifyPageToken method
`if (!getProtectedPages().contains(request.getRequestURI())) {
			return;
		}`

This will not verify the page at all if the page was not explicitly declared as protected, which is not necessary unless we have explicitly set org.owasp.csrfguard.Protect to True.

I would suggest removing this portion of the code, because verifyPageToken will not be reached if the page is not protected (already checked on line 1 of isValidRequest() ).

Another solutions is to modify this code as follows 
`if (isProtectEnabled() && !getProtectedPages().contains(request.getRequestURI())) {
			return;
		}`

Best,
Ivan

**Comment by aramrami** [comment]
Please create a pull request and I will merge it
