### ISSUE TITLE
CSRFGuard generate new tokens if jsessionID is in the URL.

### ISSUE THREAD

**Issue by glitchcube** [aramrami/OWASP-CSRFGuard#111]
Before the application server knows if the browser accepts cookies, it sends the jsessionsID via the URL. If the browser accepts cookies, the browser stores the jsessionID and the application server stops sending the sessionID via the URL.

The problem is if the browser is not accepting cookies. Then the jsessionID is sendt for every request to the server. Then problem here is that the CSRFGuard generates new token each time it makes a request to the server. But when the CSRFGuard does the check to see if the token is valid, it seems that it is using the first token it generated. 

Not sure how to fixed this issue at the time, but hope someone can have a look at it.

**Comment by forgedhallpass** [comment]
The code-base (including the part that generates and validates tokens) has been heavily reworked, improved and extended with new functionalities. The new release candidate version can be found on the official repository under [releases](https://github.com/OWASP/www-project-csrfguard/releases).

Feel free to try it out and provide feedback.

**Comment by forgedhallpass** [comment]
@glitchcube since I haven't heard back from you, I am closing the issue. Feel free to re-open it on the official repository: https://github.com/OWASP/www-project-csrfguard
