### ISSUE TITLE
failure to define at least one action

### ISSUE THREAD

**Issue by glitchcube** [aramrami/OWASP-CSRFGuard#112]
When trying to load CSRFGuard there comes this error if no action is specified.
"failure to define at least one action".

This error comes from this line in org.owasp.csrfguard.config.PropertiesConfigurationProvider.java

`/** ensure at least one action was defined **/`
`			if (actions.size() <= 0) {
				throw new IOException("failure to define at least one action");
			}`

Is there a reason for this check? Why do we have to define an action? From the documentation (https://www.owasp.org/index.php/CSRFGuard_3_Configuration) I can not see that this is needed to be done. 

I got this error when trying to reproduce #102

**Comment by tamilsweet** [comment]
It looks like you used only the properties listed in #102, you should leave other properties to default values.

In the properties file, actions specify how to respond to attacks.
eg.
```
org.owasp.csrfguard.action.Redirect=org.owasp.csrfguard.action.Redirect
org.owasp.csrfguard.action.Redirect.Page=%servletContext%/error.html
```
With the above config, if CSRF attack is detected, the request will be redirected to the html file error.html in the servlet context.

Without any action configured, the CSRFGuard library cannot do anything and hence the exception.

**Comment by forgedhallpass** [comment]
As @tamilsweet mentioned. Not providing at least one action would be like not enabling CSRFGuard, but with the additional performance overhead, which would defeat the purpose of the solution. Currently the documentation that best describes the properties can be found within the configuration file.

In the meantime the code-base has been heavily reworked, improved and extended with new functionalities. The new release candidate version can be found on the official repository under [releases](https://github.com/OWASP/www-project-csrfguard/releases).

**Comment by forgedhallpass** [comment]
Explanation has been provided, hence closing the issue.
