### ISSUE TITLE
Issue with fix for disabling ajax requests

### ISSUE THREAD

**Issue by Woodham** [aramrami/OWASP-CSRFGuard#119]
There is a previous ticket about this here: https://github.com/aramrami/OWASP-CSRFGuard/issues/75 and a subsequent pull request to fix it here: https://github.com/aramrami/OWASP-CSRFGuard/pull/76 

However, I believe there is an issue with this fix - by adding the token to the template for the Javascript, there is a risk that the token is cached by the browser and fail for new sessions.

It makes more sense to me for the function to look like this - 

```
if(isValidDomain(document.domain, "%DOMAIN_ORIGIN%")) {
		/** optionally include Ajax support **/
		if(%INJECT_XHR% == true) {
			if(navigator.appName == "Microsoft Internet Explorer") {
				hijackExplorer();
			} else {
				hijackStandard();
			}
                } // <<<<<<<CHANGE HERE>>>>>>
		
		var xhr = window.XMLHttpRequest ? new window.XMLHttpRequest : new window.ActiveXObject("Microsoft.XMLHTTP");
		var csrfToken = {};
		xhr.open("POST", "%SERVLET_PATH%", false);
		xhr.setRequestHeader("FETCH-CSRF-TOKEN", "1");
		xhr.send(null);
		
		var token_pair = xhr.responseText;
		token_pair = token_pair.split(":");
		var token_name = token_pair[0];
		var token_value = token_pair[1];

                 XMLHttpRequest.prototype.onsend = function(data) {
			if(isValidUrl(this.url)) {
				this.setRequestHeader("X-Requested-With", "XMLHttpRequest")
				this.setRequestHeader(token_name, token_value);
			}
		};
		
		
		/** update nodes in DOM after load **/
		addEvent(window,'unload',EventCache.flush);
		addEvent(window,'DOMContentLoaded', function() {
			injectTokens(token_name, token_value);
		});
	} else {
		alert("OWASP CSRFGuard JavaScript was included from within an unauthorized domain!");
	}
```

i.e. to always obtain the token key and value via ajax regardless of whether hijacking/protecting  ajax requests is disabled. It doesn't make sense to me to conflate these two concepts.

This way there are no issues with caching the JavascriptServlet.

**Comment by aramrami** [comment]
Please provide a merge request and I will accept it.
