### ISSUE TITLE
Title should be CSRFGuard instead of CSFRGuard in index.md

### ISSUE THREAD

**Issue by lok0919** [aramrami/OWASP-CSRFGuard#120]
The title should be CSRFGuard instead of CSFRGuard in index.md.

layout | title | site_side | tags | project | type
-- | -- | -- | -- | -- | --
col-sidebar | CS~~FR~~RFGuard | true | csrfguard | true | tool

**Comment by forgedhallpass** [comment]
The repository has been migrated to its official location: https://github.com/OWASP/www-project-csrfguard where the requested change has already been made.
