### ISSUE TITLE
Provide support for stateless web applications

### ISSUE THREAD

**Issue by forgedhallpass** [aramrami/OWASP-CSRFGuard#122]
Introducing a new layer of abstraction for storing tokens would allow more flexibility. Offering a non-session bound reference implementation would be desirable.

**Comment by mmedjahed** [comment]
+1

**Comment by forgedhallpass** [comment]
Fixed in the new code-base. The new release candidate version can be found under [releases](https://github.com/OWASP/www-project-csrfguard/releases) on the official repository.

**Comment by forgedhallpass** [comment]
Related issue in the official repository: https://github.com/OWASP/www-project-csrfguard/issues/4
