### ISSUE TITLE
Provide support for on-demand or time-based token rotation/invalidation

### ISSUE THREAD

**Issue by forgedhallpass** [aramrami/OWASP-CSRFGuard#124]
A session can remain active for a long period of time if there is user activity, so an attacker has higher chances to acquire the token(s). A client-initiated or time-based token rotation/invalidaton could help mitigating this issue.

**Comment by tamilsweet** [comment]
In my usage, we use session timeout from backend once the backend session is invalidated, the token becomes invalid as well because its tied to the HttpSession.
@forgedhallpass Can you give a try to this method?

**Comment by forgedhallpass** [comment]
> A _session_ can remain _active_ for a _long period of time_ if there is user activity, so an attacker has higher chances to acquire the token(s).

^ That is why I would consider a periodical rotation of the tokens. Besides that, I would like the solution to be independent from the session. (see #122)

**Comment by forgedhallpass** [comment]
On a second thought, for this functionality to provide at least a slight improvement from a security standpoint, it would require a significant amount of resources + complexity and still the outcome would be negligible, hence closing it.
