### ISSUE TITLE
Favicon.ico

### ISSUE THREAD

**Issue by em-ocean** [aramrami/OWASP-CSRFGuard#13]
There is a problem with favicon.ico. Adding "org.owasp.csrfguard.unprotected.Favicon=%servletContext%/img/favicon.ico" or "org.owasp.csrfguard.unprotected.Favicon=*/favicon.ico" to config has no effect

**Comment by gabrielbratescu** [comment]
I dit it this way:
org.owasp.csrfguard.unprotected.ICO=*.ico

**Comment by aramrami** [comment]
Is this solve your issue?
org.owasp.csrfguard.unprotected.ICO=*.ico
