### ISSUE TITLE
Error coming in the application:request token does not match page token

### ISSUE THREAD

**Issue by ashish-nayal** [aramrami/OWASP-CSRFGuard#138]
I am trying to implement CSRFGuard 3.1.0 in my project.The code works fine when I run a page for first time but when I again run the same page it gives error:
**WARNING: potential cross-site request forgery (CSRF) attack thwarted (user:admin, ip:127.0.0.1, method:POST, uri:/demo/studentList, error:request token does not match page token)**

Kindly help me in resolving the issue.

**Comment by forgedhallpass** [comment]
A new release candidate can be found under [releases](https://github.com/OWASP/www-project-csrfguard/releases) on the official repository.

Feel free to try it out and let me know if the issue still persists.

**Comment by forgedhallpass** [comment]
@ashish-nayal since I haven't heard back from you, I am closing the issue.
