### ISSUE TITLE
Cant extend CsrfGuardFilter

### ISSUE THREAD

**Issue by deepak229** [aramrami/OWASP-CSRFGuard#152]
Why should this class be final?

I have a use case where I do not want to do CSRF filtering for requests that has some characteristics. Say, it is Token based which is called from some other Internal micro-service or a Public Rest API with Bearer Token. I would like to override this class and add some custom conditions before I actually run through CSRFGuard. Is that kind of logic allowed? 

Is there a strong reason to make this class final?

**Comment by deepak229** [comment]
@aramrami. can this class be made non-final. This is limiting us to not extend the behavior provided by the library.

**Comment by forgedhallpass** [comment]
@deepak229 the code-base has been moved to the [official repository](https://github.com/OWASP/www-project-csrfguard). I don't have access on this one, but will accept your pull-request there, or can commit it for you.

**Comment by deepak229** [comment]
Thanks for the reply. I'll open a pull request there.

**Comment by aramrami** [comment]
I will change the readme to indicate that all code are now in the official OWASP CSRFGuard repo.
