### ISSUE TITLE
charset encoding is missing from JavaScriptServlet responses

### ISSUE THREAD

**Issue by jellisgwn** [aramrami/OWASP-CSRFGuard#154]
Both the Javascript and the token response are returned without a charset:

```
HTTP/1.1 200 OK 
Cache-Control: private, maxage=28800 
Cache-Control: no-cache, no-store, must-revalidate 
Connection: close 
Date: Thu, 19 Nov 2020 16:13:50 GMT 
Transfer-Encoding: chunked 
Content-Type: text/javascript 
Content-Encoding: gzip 
```

**Comment by forgedhallpass** [comment]
I don't have anything against this modification, although I don't see the importance either as the JavaScriptServlet does not accept any kind of user input. Could you please provide an explanation?

**Comment by jellisgwn** [comment]
This was reported by a scanning tool. Agree it's a minor issue, one of those not strictly necessary but the right things to do.

**Comment by jellisgwn** [comment]
Closing and will restart discussion in the new repo.
