### ISSUE TITLE
CSRF GUARD 3.1 doesn't work with proxy

### ISSUE THREAD

**Issue by saad9519** [aramrami/OWASP-CSRFGuard#156]
Hi,

I tried to use CSRF GUARD 3.1.0 in my project and it worked fine. However when I use a proxy I can't use my application. It detects an attack.
Thanks for the help

**Comment by forgedhallpass** [comment]
You'd need to give more details than that. Could it be that you have the  'referer-match-domain' and 'referer-pattern' configured to a specific domain name and the proxy you are using is modifying the request hence the exception? Have you compared the requests before and after the proxy?
