### ISSUE TITLE
CSRFGUARD is switching user sessions

### ISSUE THREAD

**Issue by saad9519** [aramrami/OWASP-CSRFGuard#157]
Hi,
I implemented CSRF GUARD. When I use it with the proxy the users when they reach a large number they start to see sessions from other people who are logged in at the same time. Do you have any idea or clue where the problem comes from knowing that the user who has the session changed to another has the same JSESSIONID as the real owner of the session?

Thanks for the help

**Comment by forgedhallpass** [comment]
Hello,

The project has been moved to the [official repository](https://github.com/OWASP/www-project-csrfguard). Please try out the latest version from [here](https://github.com/OWASP/www-project-csrfguard/releases/tag/4.0.0-rc1). 

If the issue persists, provide a more clear and detailed explanation of the problem. What do you mean by users see sessions from other users? How? Why do users have their sessions altered, why would two users have the same session id and why do you suspect that it has anything to do with CSRFGuard?

**Comment by forgedhallpass** [comment]
@saad9519 since we haven't received any response I am closing the issue.
