### ISSUE TITLE
v3.1.0 does not available on Maven Central

### ISSUE THREAD

**Issue by Krasnyanskiy** [aramrami/OWASP-CSRFGuard#17]
I found `CSRFGuard` library on `Maven Central`, but the latest version is `3.0.0`. Declared dependencies in [Readme](https://github.com/aramrami/OWASP-CSRFGuard#using-with-maven) are broken.

```xml
<dependency>
    <groupId>org.owasp</groupId>
    <artifactId>csrfguard</artifactId>
    <version>3.1.0</version>
</dependency>
```

So what about publishing it on `Maven Central`?

**Comment by aramrami** [comment]
No thing in Maven Central. You can download the binary 3.1.0 version from
OWASP project page or compile it by yourself.
I want some one to help me to publish in Maven Central because I don't have
enough time to do it.
Azzeddine


2015-09-02 22:25 GMT+02:00 Alexander Krasnyanskiy <notifications@github.com>
:

**Comment by Krasnyanskiy** [comment]
Before publishing on Maven Central it would be nice to clean up the code. Remove `final` access modifier  from classes to make them extendable and to improve code extensibility in general.

**Comment by Krasnyanskiy** [comment]
@aramrami Do you have change list for version 3.1.0?

**Comment by aramrami** [comment]
This is in the roudmap but I am alone and I cannot do all change and
responds to all request.
Could you help for this cleaning ?
Azzeddine

2015-09-02 22:46 GMT+02:00 Alexander Krasnyanskiy <notifications@github.com>
:

**Comment by Krasnyanskiy** [comment]
Sure.

**Comment by aramrami** [comment]
Thank you very much.
You can do the change in GitHub.
I will ad your name and email in the OWASP Project and your role is:

- Clean the code to publish it in Maven Central.

I will share with you after AppSec USA the new techniques to protect
against CSFR and I will add them in the version 4.0 of the project.
Azzeddine

2015-09-02 23:01 GMT+02:00 Alexander Krasnyanskiy <notifications@github.com>
:
