### ISSUE TITLE
Wrong properties in wiki

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#21]
In configuration page https://www.owasp.org/index.php/CSRFGuard_3_Configuration there are mistakes:

Wrong:
`org.owasp.csrfguard.action.class.Redirect=org.owasp.csrfguard.actions.Redirect`
Right:
`org.owasp.csrfguard.action.Redirect=org.owasp.csrfguard.action.Redirect`

Wrong:
`org.owasp.csrfguard.action.Redirect.ErrorPage=/Owasp.CsrfGuard.Test/error.html`
Right: 
`org.owasp.csrfguard.action.Redirect.Page=/Owasp.CsrfGuard.Test/error.html`

I don't have an account, so please change it.

**Comment by aramrami** [comment]
This is related to version 3 not to version 3.1.1 witch is correct.
I will delete this wiki and create a new one for version 3.1.1.
Thanks for your remarks.
Azzeddine
