### ISSUE TITLE
tag.jsp in csrfguard-test project is broken

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#26]
The page `http://localhost:8000/tag.jsp` throws the HTTP Status 500 - `"org.apache.jasper.JasperException: /tag.jsp (line: 26, column: 28) No tag "token-name" defined in tag library imported with prefix "csrf"`. 

It is expected, since `csrfguard.tld` doesn't exist in `csrfguard-test`.

**Comment by aramrami** [comment]
I will look to that. Thanks.
