### ISSUE TITLE
form without "action" attribute doesn't have hidden CSRF token 

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#27]
Steps:
1. Create page with form:
   
   ```
   <script src="/JavaScriptServlet"></script>
   <form name="test1" method="post">
       <input type="text" name="text" value="text"/>
       <input type="submit" name="submit" value="submit"/>
   </form>
   ```
2. Set `org.owasp.csrfguard.JavascriptServlet.injectIntoForms = true`

Expected result:
`<input type="hidden" name="OWASP_CSRFTOKEN" value="...">` is inserted into form.

Actual result:
Nothing is inserted.

Resolution:
Change function `injectTokenAttribute` in `csrfguard.js`.

**Comment by aramrami** [comment]
I already merged your request in the master branch. Let me see. May be I will release a minor version

**Comment by bronogard** [comment]
@aramrami thanks in advance for considering to release a minor version. 👍

**Comment by glitchcube** [comment]
I see there have been some changes done here. Is this issue resolved @aramrami ?

**Comment by aramrami** [comment]
No not solved.
If you can code the solution and create a pull request. I will merge it after.
