### ISSUE TITLE
"onunload" events doesn't fire on page with CsrfGuard

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#28]
Steps:

1. Create page

    ```
    <script src="/JavaScriptServlet"></script>
    <body onunload="console.log('unloadhappens')">
        <form name="test1" method="post">
            <input type="text" name="text" value="text"/>
            <input type="submit" name="submit" value="submit"/>
        </form>
    </body>
    ```

2. Load this page in Chrome, open Developer Tools (F12), switch to `"Console"` tab and check `Preserve log` option.

3. Reload page.

Expected result:
`"unloadhappens"` text must appear in `Console`.

Actual result:
Nothing appears in `Console`.

Explanation:
`EventCache` object in `csrfguard.js` overwrites existing "onunload" events. 

Resolution:
Remove the 73th line:
    ```
    item[0][item[1]] = null;
    ```

**Comment by 40rn05lyv** [comment]
Actually, I recommend to completely remove the "flush" method - it provides anti-leaking functionality for IE6-7 (their usage is 0.12% according to http://gs.statcounter.com/#all-browser_version-ww-monthly-201507-201509-bar). Memory leaking was fixed completely in IE8 and no other browser had such problems (http://blogs.msdn.com/b/gpde/archive/2009/08/03/javascript-memory-leak-detector-v2.aspx).

**Comment by aramrami** [comment]
Ok I will remove this line.
