### ISSUE TITLE
trim property values

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#29]
It's good practice to trim property values to avoid stupid mistakes (like I did).

Resolution:
Change from
   
	public static String propertyString(Properties properties, String propertyName) {
		String value = properties.getProperty(propertyName);
		value = commonSubstitutions(value);
		return value;
	}

to

	public static String propertyString(Properties properties, String propertyName) {
		String value = properties.getProperty(propertyName);
		value = commonSubstitutions(value);
                if (value != null) {
                        value.trim();
                }
		return value;
	}

etc.

**Comment by aramrami** [comment]
In the version 4.0 we did a lot correction in the Input Validation in CSRFGuard. Please post a Pull Request to include this in the version 3.1.0 of the code.
