### ISSUE TITLE
CSRF token can be inserted multiple times to the same attribute

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#31]
In cases, when CsrfGuard.js is loaded multiple times in the same page (e.g. old projects that have multiple "include"s; pages that are dependent between each other) the "src", "action", "href" attributes can have multiple `OWASP_CSRFTOKEN` parameters.

The same will happen if, for example, OWASP_CSRFTOKEN was already set in *.jsp code.

See `injectTokenAttribute` function.

Low priority.

**Comment by 40rn05lyv** [comment]
**Solution:** (change `injectTokenAttribute` function and add couple of methods):

    /** inject tokens as query string parameters into url **/
    function injectTokenAttribute(element, attr, tokenName, tokenValue, pageTokens) {
        var location = element.getAttribute(attr);
        
        if(location != null && isValidUrl(location)) {
            var uri = parseUri(location);
            var value = (pageTokens[uri] != null ? pageTokens[uri] : tokenValue);
            
            if (getParameter(location, tokenName) != tokenValue) {
                location = setParameter(location, tokenName, tokenValue);
                
                try {
                    element.setAttribute(attr, location);
                } catch (e) {
                    // attempted to set/update unsupported attribute
                }
            }
        }
    }

    function parseParameters(url) {
        var query_string = {};
        var parser = document.createElement('a');
        parser.href = url;
        var query = parser.search.substr(1);
        var vars = query.split("&");
        for (var i=0;i<vars.length;i++) {
            var pair = vars[i].split("=");
            // If first entry with this name
            if (typeof query_string[pair[0]] === "undefined") {
                query_string[pair[0]] = decodeURIComponent(pair[1]);
                // If second entry with this name
            } else if (typeof query_string[pair[0]] === "string") {
                var arr = [ query_string[pair[0]],decodeURIComponent(pair[1]) ];
                query_string[pair[0]] = arr;
                // If third or later entry with this name
            } else {
                query_string[pair[0]].push(decodeURIComponent(pair[1]));
            }
        }
        return query_string;
    }
    
    function getParameter(url, key) {
        return parseParameters(url)[key];
    }

**Comment by aramrami** [comment]
Hi,
If the given solution helped you please close the issue don't keep it open?

**Comment by 40rn05lyv** [comment]
Hi,
Better solution that helped me is in #40.

I didn't closed this issue, because I thought that issue should be closed only if it is fixed in repository.

I can create 1 big pull request for all defects that were submitted and solved by me.

**Comment by aramrami** [comment]
Yes please do it so I can close it.
Thanks
