### ISSUE TITLE
Unable to remove action in overlay file

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#39]
**Steps:**

1. Configure overlay functionality with `Owasp.CsrfGuard.properties` and `Owasp.CsrfGuard.overlay.properties` files.
2. Set in the first file:

    ```
org.owasp.csrfguard.action.Error=org.owasp.csrfguard.action.Error
org.owasp.csrfguard.action.Error.Code=403
org.owasp.csrfguard.action.Error.Message=CSRF security token is not found or invalid.
    ```
3. Set in the second file

    ```
org.owasp.csrfguard.action.Error=
org.owasp.csrfguard.action.Error.Code=
org.owasp.csrfguard.action.Error.Message=
    ```

**Expected result:**
"Error" action is not executed

**Actual result:**
`java.lang.ClassNotFoundException` is thrown from `org.owasp.csrfguard.config.PropertiesConfigurationProvider` class, line 151:

 `IAction action = (IAction) Class.forName(actionClass).newInstance();`

during Tomcat startup.

**Solution:**
Before calling `Class.forName` you should check whether it is `null` or empty string.

**Comment by aramrami** [comment]
Please create a Pull Request in order to include it in the repository. and Thanks for your help.
