### ISSUE TITLE
CsrfGuard doesn't work in IE8

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#41]
The `Owasp.CsrfGuard.js` fetches csrf token from server using AJAX POST request: 

    var xhr = window.XMLHttpRequest ? new window.XMLHttpRequest : new window.ActiveXObject("Microsoft.XMLHTTP");
    var csrfToken = {};
    xhr.open("POST", "%SERVLET_PATH%", false);
    xhr.setRequestHeader("FETCH-CSRF-TOKEN", "1");
    xhr.send(null);
    
However, in IE8, the POST request is not executed and `xhr.responseText` returns the javascript file itself!!!

This defect is described in following stackoverflow QA: http://stackoverflow.com/questions/20716781/jquery-ajax-cache-option-ie8/20717136#20717136

> "If you make a GET request in IE8 and then later make a POST request to the same URL, IE8 will incorrectly return the cached response rather than doing the POST."

**Solution:**

Change line from 

`xhr.open("POST", "%SERVLET_PATH%", false);`

to 

`xhr.open("POST", "%SERVLET_PATH%?t=" + new Date().getTime(), false);`

**Comment by aramrami** [comment]
Please send a Pull Request.
