### ISSUE TITLE
Vulnerability detected with Fortify Scan

### ISSUE THREAD

**Issue by jxboi** [aramrami/OWASP-CSRFGuard#42]
Hi,

Recently we did a source code review using Fortify and detected a few vulnerabilities in 
- CSRFGuard.cs 
- CSRFGaurdModule.cs
- RegExFilter.cs
- AppConfiguration.cs

Any kind souls able to advise. Thanks.

Below are the details,

CSRFGuard.cs, line 136 (Value Shadowing)
Fortify Priority: High Folder High
Kingdom: Input Validation and Representation
Abstract: The function detectCSRFAttempt() in CSRFGuard.cs accesses a variable in an
ambiguous way at line 136, which can leave the program open to attack.
Sink: CSRFGuard.cs:136 get_Item()

CSRFGuard.cs, line 134 (Value Shadowing)
Fortify Priority: High Folder High
Kingdom: Input Validation and Representation
Abstract: The function detectCSRFAttempt() in CSRFGuard.cs accesses a variable in an
ambiguous way at line 134, which can leave the program open to attack.
Sink: CSRFGuard.cs:134 get_Item()

CSRFGuardModule.cs, line 59 (Poor Error Handling: Empty Catch Block)
Fortify Priority: Low Folder Low
Kingdom: Errors
Abstract: The method filterHTMLResponse() in CSRFGuardModule.cs ignores an exception on
line 59, which could cause the program to overlook unexpected states and conditions.
Sink: CSRFGuardModule.cs:59 CatchBlock()

RegExFilter.cs, line 72 (Poor Logging Practice: Use of a System Output Stream)
Fortify Priority: Low Folder Low
Kingdom: Encapsulation
Abstract: Using WriteLine() rather than a dedicated logging facility makes it difficult to
monitor the behavior of the program.
Sink: RegExFilter.cs:72 FunctionCall: WriteLine()

AppConfiguration.cs, line 46 (XML External Entity Injection)
Fortify Priority: High Folder High
Kingdom: Input Validation and Representation
Abstract: XML parser configured in AppConfiguration.cs:46 does not prevent nor limit external
entities resolution. This can expose the parser to an XML External Entities attack.
Sink: AppConfiguration.cs:46 Load(...) : XML reader instantiated allowing DTD
processing()

**Comment by 40rn05lyv** [comment]
Hi, @jxboi 

This repository is for Java implementation of CSRFGuard. And code that you scanned is written in C#. 
https://www.owasp.org/index.php/.Net_CSRF_Guard
https://code.google.com/p/owasp-code-central/

I didn't found official .NET CSRFGuard repository in Github, I suppose it's no longer supported.
Maybe @aramrami knows more.

Anyway, found defects don't look hard to fix.

**Comment by aramrami** [comment]
Hi,
CSRFGuard .NET has no link with CSRFGuard (for Java).
Please ask the project leader directly.

I support only the CSRFGuard project (for Java).

Azzeddine RAMRAMI

2015-11-18 7:32 GMT+01:00 chornoslyv <notifications@github.com>:

**Comment by jxboi** [comment]
Got it. Thanks for the response.
