### ISSUE TITLE
Problems with injecting token into form in old IE

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#44]
In old IE (IE7 and some newer IE in compatibility mode) <input> tag has invalid name.
For example, instead of `<input name="csrf" value="...">` there is `<input submitName="csrf" value="...">`. 

It's some ancient IE defect.

**Solution:**
Change `injectTokenForm` function so that input element was created correctly:

```
var input; 
try {
    // Hack for IE7- and compat modes
    input = document.createElement('<input type="hidden" name="' + tokenName + '" value="' + tokenVal+'" />');
} catch (error) {
    // Normal way
    input = document.createElement("input");
    input.setAttribute("type", "hidden");
    input.setAttribute("name", tokenName);
    input.setAttribute("value", tokenVal);
}
form.appendChild(input);
```

**Comment by aramrami** [comment]
If you want that in the repository please send a Pull Request. Thanks I will close this issue.
