### ISSUE TITLE
css is loading very slow

### ISSUE THREAD

**Issue by vdl1992** [aramrami/OWASP-CSRFGuard#46]
Hi, I implemented the csrfguard in my project and everything is working fine but when I load a page it first loads the html without layout and after a refresh it loads te css. This only occurs with csrfguard enabled.I allready use the following config properties but they don't seem to do anything as I can still see that csrfguard is analyzing these type of files in the console output.

org.owasp.csrfguard.unprotected.js=_.js
org.owasp.csrfguard.unprotected.JavaScript=_.js
org.owasp.csrfguard.unprotected.css=_.css
org.owasp.csrfguard.unprotected.png=_.png
org.owasp.csrfguard.unprotected.jpg=_.jpg
org.owasp.csrfguard.unprotected.ico=_.ico
org.owasp.csrfguard.unprotected.gif=_.gif
org.owasp.csrfguard.unprotected.svg=_.svg

**Comment by afattahi54** [comment]
Is your css and js loaded twice, you can check it with Firefox web development tool ?!

**Comment by mehmudjan** [comment]
This is issue still persists on the recent version of csrf guard, tested on version 4.0.0
