### ISSUE TITLE
multipart forms

### ISSUE THREAD

**Issue by MatthewFellows** [aramrami/OWASP-CSRFGuard#49]
I'm really unclear if this is a bug or a configuration issue...  I've submitting a multipart form (File upload) and the process checks the session stored token against: request.getParameter(getTokenName())

In a multipart request the token needs to be access a different way as the inputstream will have already been read.  

What are we meant to do about mutipart forms?

**Comment by 40rn05lyv** [comment]
There are 2 ways to process multipart requests

1. Use `javax.servlet.annotation.MultipartConfig` annotation - in this case all parameters (including TokenName) will be available in CSRFGuardFilter.
2. Write custom filter that will parse inputstream using Apache Commons Fileupload https://commons.apache.org/proper/commons-fileupload/ (you'll need to create custom  HttpServletRequestWrapper around ServletRequest and overwrite getParameter(..), getParameterNames(), getParameterValues(..), getParameterMap() methods) and place this filter before CSRFGuardFilter.

**Comment by ReginaldoSantos** [comment]
So @40rn05lyv, it is not a bug, but it is some kind of missing implementation, right?

**Comment by 40rn05lyv** [comment]
@ReginaldoSantos CsrfGuard uses `request.getParameter()` method. It's developer's duty to parse multipart request and make sure that `getParameter()` works as expected.

**Comment by ReginaldoSantos** [comment]
Hummm @40rn05lyv , I see. Thanks for the fast reply.

**Comment by Souchong** [comment]
I made a custom filter for this (40rn05lyv second proposition). 

The filter : 
`public class CsrfGuardFilterUploadWorkaround implements Filter {

	private static final Logger LOGGER = LoggerFactory.getLogger(CsrfGuardFilterUploadWorkaround.class);

	@Override
	public void destroy() {
	}
	
	@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
		HttpServletRequest req = (HttpServletRequest) request;

		CsrfGuard csrfGuard = CsrfGuard.getInstance();
		if (csrfGuard.isEnabled()) {
			// What is a readable CsrfGuard token : 
			// Request validation : [...]if (csrfGuard.isValidRequest(httpRequest, httpResponse)) {Ok} else {Ko}
			// Case 1 : CsrfGuard::verifyAjaxToken => use getHeader function
			// => String tokenFromRequest = request.getHeader(getTokenName());
			// Case 2 : CsrfGuard::verifyPageToken => use getParameter function
			// => String tokenFromRequest = request.getParameter(getTokenName());
			// Case 3 : CsrfGuard::verifySessionToken => use getParameter function
			// => String tokenFromRequest = request.getParameter(getTokenName());	

			// Multipart case : getParameter does not retrieve token in multipart

			// Check if a CSRFGuard readable token could be find
			String tokenName = csrfGuard.getTokenName();
			String tokenValue = null;
			if (StringUtils.isNotEmpty(tokenName)) {
				// Nominal case 1 : try to retrieve CSRF token in request headers (Ajax)
				tokenValue = req.getHeader(tokenName);			
				if (StringUtils.isEmpty(tokenValue)) {
					// Case 1 failed 
					// Nominal case 2 & 3 : try to retrieve CSRF token in request Parameters 
					tokenValue = request.getParameter(tokenName);
				}				
			}

			
			// Case 1, 2, 3 failed
			// Check if we are in Multipart case
			if (StringUtils.isEmpty(tokenValue)) {
				if (ServletFileUpload.isMultipartContent(req)) {
					
					// Create HttpServletRequestWrapper in order to read CSRF token (if exist) 
					MutableHttpServletRequest mutableRequest = new MutableHttpServletRequest(req);
					
					// Resolve CSRF token value
					CommonsMultipartResolver commonsMultipartResolver = new CommonsMultipartResolver();
					MultipartHttpServletRequest multipartRequest = commonsMultipartResolver.resolveMultipart(mutableRequest);
					tokenValue = multipartRequest.getParameter(tokenName); 	
					
					// Reinitialize Input Stream for further use
					mutableRequest.resetInputStream();
						
					if (StringUtils.isNotEmpty(tokenValue)) {
						// The workarounds (twice tested) 
						LOGGER.debug("CsrfFilter.doFilter : token [{}] found in multipart request => let CsrfGuard do its work", tokenValue);
						
						// First method
						// Add token in map parameters so that CsrfGuard could get it from getParameter function  
						mutableRequest.addParameter(tokenName, tokenValue);
		
						// Second method
						// Add header so that CsrfGuard thinks it is an Ajax request
						// mutableRequest.putHeader("X-Requested-With", "CSRFGuardUploadWorkaround");
						// mutableRequest.putHeader(tokenName, tokenValue);
						
						chain.doFilter(mutableRequest, response);
					} else {
						LOGGER.warn("CsrfFilter.doFilter : multipart request without token => probably a CSRF attack");
						chain.doFilter(request, response);
					}
				} else {
					LOGGER.debug("CsrfFilter.doFilter : non multipart request without token => probably a CSRF attack");
					chain.doFilter(request, response);		
				}
			} else {
				LOGGER.debug("CsrfFilter.doFilter : token [{}] found in request => let CsrfGuard do its work", tokenValue);
				chain.doFilter(request, response);		
			}
		} else {
			LOGGER.debug("CsrfFilter.doFilter : CSRFGuard disable");
			chain.doFilter(request, response);		
		}
	}

	@Override
	public void init(FilterConfig arg0) throws ServletException {
	}
}
` 

MutableHttpServletRequest.java
`public final class MutableHttpServletRequest extends HttpServletRequestWrapper {

	private static final Logger LOGGER = LoggerFactory.getLogger(MutableHttpServletRequest.class);
	
	// holds custom header and value mapping
	private final Map<String, String> customHeaders;
	private Map<String, String[]> parameterMap;
	private byte[] rawData;
	private HttpServletRequest request;
	private ResettableServletInputStream servletStream;
	
	public MutableHttpServletRequest(HttpServletRequest request) {
		super(request);
		this.request = request;
		this.servletStream = new ResettableServletInputStream();
		this.customHeaders = new HashMap<>();
		try {
			InputStream input = request.getInputStream();
			rawData = IOUtils.toByteArray(input);
			servletStream.stream = new ByteArrayInputStream(rawData);
		} catch (IOException e) {
			LOGGER.info("MutableHttpServletRequest::MutableHttpServletRequest failed to read content");
		}
	}

	public void putHeader(String name, String value) {
		this.customHeaders.put(name, value);
	}
	
	@Override
	public String getHeader(String name) {
		// check the custom headers first
		String headerValue = customHeaders.get(name);
		if (headerValue != null) {
			return headerValue;
		}

		// else return from into the original wrapped object
		return ((HttpServletRequest) getRequest()).getHeader(name);
	}

	@Override
	public Enumeration<String> getHeaderNames() {
		// create a set of the custom header names
		Set<String> set = new HashSet<>(customHeaders.keySet());

		// now add the headers from the wrapped request object
		@SuppressWarnings("unchecked")
		Enumeration<String> e = ((HttpServletRequest) getRequest()).getHeaderNames();
		while (e.hasMoreElements()) {
			// add the names of the request headers into the list
			String n = e.nextElement();
			set.add(n);
		}

		// create an enumeration from the set and return
		return Collections.enumeration(set);
	}
	
	public void addParameter(String name, String value) {
		if (parameterMap == null) {
			parameterMap = new HashMap<String, String[]>();
			parameterMap.putAll(((HttpServletRequest) getRequest()).getParameterMap());
		}
		String[] values = parameterMap.get(name);
		if (values == null) {
			values = new String[0];
		}
		List<String> list = new ArrayList<String>(values.length + 1);
		list.addAll(Arrays.asList(values));
		list.add(value);
		parameterMap.put(name, list.toArray(new String[0]));
	}

	@Override
	public String getParameter(String name) {
		if (parameterMap == null) {
			return ((HttpServletRequest) getRequest()).getParameter(name);
		}

		String[] strings = parameterMap.get(name);
		if (strings != null) {
			return strings[0];
		}
		return null;
	}

	@Override
	public Map<String, String[]> getParameterMap() {
		if (parameterMap == null) {
			return ((HttpServletRequest) getRequest()).getParameterMap();
		}

		return Collections.unmodifiableMap(parameterMap);
	}

	@Override
	public Enumeration<String> getParameterNames() {
		if (parameterMap == null) {
			return ((HttpServletRequest) getRequest()).getParameterNames();
		}

		return Collections.enumeration(parameterMap.keySet());
	}

	@Override
	public String[] getParameterValues(String name) {
		if (parameterMap == null) {
			return ((HttpServletRequest) getRequest()).getParameterValues(name);
		}
		return parameterMap.get(name);
	}
	
	public void resetInputStream() {
		servletStream.stream = new ByteArrayInputStream(rawData);
	}

	@Override
	public ServletInputStream getInputStream() throws IOException {
		if (rawData == null) {
			rawData = IOUtils.toByteArray(this.request.getReader());
			servletStream.stream = new ByteArrayInputStream(rawData);
		}
		return servletStream;
	}

	@Override
	public BufferedReader getReader() throws IOException {
		if (rawData == null) {
			rawData = IOUtils.toByteArray(this.request.getReader());
			servletStream.stream = new ByteArrayInputStream(rawData);
		}
		return new BufferedReader(new InputStreamReader(servletStream));
	}	
	
	// ServletInputStream implementation
	private class ResettableServletInputStream extends ServletInputStream {

		private InputStream stream;

		@Override
		public int read() throws IOException {
			return stream.read();
		}

		@Override
		public boolean isFinished() {
			return ((ServletInputStream)stream).isFinished();
		}

		@Override
		public boolean isReady() {
			return ((ServletInputStream)stream).isReady();
		}

		@Override
		public void setReadListener(ReadListener readListener) {
			((ServletInputStream)stream).setReadListener(readListener);
		}
	}
	
}`

And the web.xml : 
`<?xml version="1.0" encoding="UTF-8"?>
<web-app ...>
[...]
	
	<filter>
		<filter-name>CsrfGuardFilterUploadWorkaround</filter-name>
		<filter-class>...CsrfGuardFilterUploadWorkaround</filter-class>
	</filter>
[...]
	
	<filter>
		<filter-name>CSRFGuard</filter-name>
		<filter-class>org.owasp.csrfguard.CsrfGuardFilter</filter-class>
	</filter>
[...]      
</web-app>`

Hope it helps.
