### ISSUE TITLE
Not clear where to set http status and headers for invalid vs. valid request

### ISSUE THREAD

**Issue by christopherbalz** [aramrami/OWASP-CSRFGuard#5]
I'd like to set the http status of the http response to 401, and the header to no-cache, when the request is invalid (for example, when the token is bad).  But looking at the code here and the code that it calls (`isValidRequest`, and so on):

  https://github.com/aramrami/OWASP-CSRFGuard-3/blob/08e19cf39570d03275b280be72a027f1983a486f/csrfguard/src/main/java/org/owasp/csrfguard/CsrfGuardFilter.java#L87

there seems to be no point where the code that calls 'doFilter' can specify a different response for the invalid case vs. the valid case.

Is this not necessary because the only non-attacker case of an invalid token is considered to be under session timeout, in which case the Owasp CsrfGuard filter won't be reached since it is located after the session timeout check?

Otherwise: I understand that some may desire to send an http 200 in order to minimize the information given out to potential attackers, but imo a brute force attack should instead by handled by a rate limiter.   Also what if somehow there is a problem in the session timeout check, or some other problem, that causes non-attacker users to reach the Owasp CsrfGuard filter with invalid tokens?

For restful webapps, one would want to set the response to no-cache so that future requests that are valid (valid token) have a chance to get fresh data.  If that's not possible, legitimate users of such webs who receive an invalid token due to a server misconfiguration, or users with stale tokens that were obtained legitimately, must know to hard-refresh (shift-refresh) the web page or manually clear their cash in order to obtain an operable webapp again.

**Comment by aramrami** [comment]
CSFRGuard is a fliter in the Java EE Web App. You can setup  the custom 401 page in the Web App not in the CSRFGuard.
