### ISSUE TITLE
Synchronous XHR

### ISSUE THREAD

**Issue by constantind** [aramrami/OWASP-CSRFGuard#51]
Is it possible to change to asynchronous XHR instead in the csrfguard javascript as it Sync XHR will be deprecated in future?

**Comment by xMort** [comment]
I would be interested in resolution to this issue as well. I hate that usage of the library introduced warning into the Console window of the modern browsers.

**Comment by ReginaldoSantos** [comment]
Indeed. For now I'm disabling it by setting async=true in my own js file:

` xhr.open("POST", "%SERVLET_PATH%", true);`

But I'm not sure if that would incur in some security flaw as well.

**Comment by constantind** [comment]
just changing it to true wont work, however it will with async promise based solution and overwriting all form submit handlers pseudo code:
foreachform(function() {
var form = this, realSubmit = form.submit;
form.submit = function() {
    getPageTokenAsync(form) {
        var d = $.Deferred();
        postAsyncAjaxWithHeader(form, d); //At this point you updating the form token and rolling a new one followed by immediate submit
        return d;
    }).then(function() {
        realSubmit.apply(form);
    });
}
}
if MITM is trying to interact in this interval will just be confirming the user already intended operation plus the token will be rolled on the server and reply will not work.

**Comment by nottoseethesun** [comment]
Is there a config option that allows the initial token to be in a `meta` tag of the root html page for the web app, like the Spring framework does it?  Then the `csrf-guard.js` file could read it from there.
