### ISSUE TITLE
Default caching parameter is incorrect and doesn't work

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#52]
Default caching parameter `org.owasp.csrfguard.JavascriptServlet.cacheControl` is incorrect and browser doesn't cache js file generated by JavascriptServlet.

Now:

`org.owasp.csrfguard.JavascriptServlet.cacheControl = private, maxage=28800`

Should be: 

`org.owasp.csrfguard.JavascriptServlet.cacheControl = public, max-age=28800`

Explanation:
1. "private" -> "public". Js file doesn't contain any client-specific information, and, thus, it can be used as "public" - it means that proxy server can cache it once for all clients.
2. "maxage" -> "max-age" - just a typo, but all browsers failed to recognize it.

Same changes must be done in `PropertiesConfigurationProvider.java`

**Comment by itsallvoodoo** [comment]
I agree with the maxage fix and submitted a pull request to fix that. However, I would like to see a good reason why caching at the proxy server level needs to be enabled by default before wanting to change that.
