### ISSUE TITLE
Code clean up needed

### ISSUE THREAD

**Issue by dlitvak** [aramrami/OWASP-CSRFGuard#53]
Hi,

I think that the idea of protecting AJAX calls against CSRF is indeed paranoid and outdated.  The reason is that the Same Origin Policy is already enough.  SOP has been with us longer than a decade.  It's widely accepted and implemented.

At any rate, 3.1 relies on SOP to request the token from the server, which the attacker cannot do.  Does not make sense to rely on SOP in 3.1 and not in 3.0 code.

Please clean up the code or let me know if I can do it.
Thanks

**Comment by 40rn05lyv** [comment]
You are wrong. Read http://stackoverflow.com/a/2581567/751200.

> But the most important part is that a script being hosted from http://whatever.com cannot READ data from http://victom.com, but it can SEND data via POST and GET.

**Comment by 40rn05lyv** [comment]
You are wrong. Read this thread:
http://security.stackexchange.com/questions/58755/how-are-ajax-requests-vulnerable-to-csrf-attacks-if-the-same-origin-policy-is-ap

> The request [from other origin] can still be sent, just not read.

**Comment by 40rn05lyv** [comment]
Hmm.. But we send X-Requested-With header, that should be blocked by browsers that support CORS (http://caniuse.com/#feat=cors). So, probably server will not recognize such request as Ajax.
