### ISSUE TITLE
Disabling Ajax support creates a bug

### ISSUE THREAD

**Issue by dlitvak** [aramrami/OWASP-CSRFGuard#54]
In CSRFGuard
                if (isAjaxEnabled() && isAjaxRequest(request)) {
                    verifyAjaxToken(request);
                } else if (isTokenPerPageEnabled()) {
                    verifyPageToken(request);
                } else {
                    verifySessionToken(request);
                }
So, if Ajax is disabled, the token is not being included in Ajax requests per csrfguard.js.  Yet, in the code above verifySessionToken is still invoked.  tokenFromRequest == null will be true.  This will be throwing an exception.

**Comment by cadrian** [comment]
As far as I understand, this is by design. You need to include the token yourself, e.g. using the provided taglib.

See https://www.owasp.org/index.php/CSRFGuard_3_Token_Injection
