### ISSUE TITLE
Stuck threads referencing isUriMatch

### ISSUE THREAD

**Issue by shatch24** [aramrami/OWASP-CSRFGuard#55]
We ran into a problem with the HashMap.get call in the UriMatch method.  Our site is a high-volume site, with a large number of pages/links. We have about 10 regular expressions on our white list of pages/links not protected. In this scenario, we've had several stuck threads.  This tends to happen when the servers are first brought online after a deploy, as the HashMap is being built.  

To get around this, we modified the variable regexPatternCache in CsrfGuard.java and made it a ConcurrentHashMap.  Because this version of the HashMap doesn't block on retrieval, it has eliminated our stuck threads.

Thanks

**Comment by MrBuddyCasino** [comment]
I agree, since CsrfGuard is a singleton used by many threads, this must be a ConcurrentHashMap. It seems development of this project has stopped? The fix is literally just one line.
