### ISSUE TITLE
Some forms are not processed in IE

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#56]
Sorry, I don't have precise steps, but I encountered this defect in my program.
In Owasp.CsrfGuard.js we have following lines:

```
    /** iterate over all elements and injection token **/
    var all = document.all ? document.all : document.getElementsByTagName('*');
    var len = all.length;

    for(var i=0; i<len; i++) {
        var element = all[i];

        /** inject into form **/
        if(element.tagName.toLowerCase() == "form") {
            if(injectForms) {
                                  injectTokenForm(element, tokenName, tokenValue, pageTokens,injectGetForms);
            }
                            .... // skipped
                    }
                    ... // skipped
           }
```

In **injectTokenForm** we create new input 

```
  function injectTokenForm(form, tokenName, tokenValue, pageTokens,injectGetForms) {
       ... //skipped
       var hidden = document.createElement("input");
       ... //skipped
      form.appendChild(hidden);
 }
```

The problem is that **document.getElementsByTagName('*')** is MUTABLE. It means that when we found `<form>` element and added `<input name="csrf" value="...">` the length of a varible **all** was changed, but we still use old **len** variable. If some form was located in the end of list - it can be skipped and user will encounter error!

Solution:
Change for loop as follows:

```
    for(var i=0; i<all.length; i++) {
                    ... // skipped
            }
```

**Comment by mchyzer** [comment]
I just got burned by this!!!!  why is it not fixed yet?

**Comment by mchyzer** [comment]
btw, this happens in chrome and FF too, and document.all is mutable too...

**Comment by mchyzer** [comment]
this looks fixed in this commit...

https://github.com/mchyzer/OWASP-CSRFGuard-1/commit/cc6ca56c8e1d34a598dd25de2c9c184c8379c901
