### ISSUE TITLE
code does not compile with JDK 1.8 because of Javadoc reported issues

### ISSUE THREAD

**Issue by ccronemberger** [aramrami/OWASP-CSRFGuard#6]
I will add this configuration to maven-javadoc-plugin to workaround the issue for now:

&lt;configuration&gt;
	&lt;additionalparam&gt;-Xdoclint:none&lt;/additionalparam&gt;
&lt;/configuration&gt;

but ideally the Javadoc should be reviewed.

**Comment by rgm3** [comment]
I believe that PR #15 fixes this issue without resorting to -Xdoclint:none.

**Comment by aramrami** [comment]
Will be solved in version 4.0
