### ISSUE TITLE
some small issues in csrfguard-test

### ISSUE THREAD

**Issue by ccronemberger** [aramrami/OWASP-CSRFGuard#7]
While running csrfguard-test I have found a few problems. I intend to work on them after the release of the project I am currently working on, which is supposed to be next week.

1 - the browser is caching the html requests (we could play with the http headers to fix this, but maybe it is better to create a servlet to replace the protect.html)
2 - in ajax.html in the ajax method, the checking of whether the csrf check worked or not is wrong: it was reporting "200: passed csrf check" even when the served page was error.html
3 - links to "http://localhost/test.html" do not work when running on port 8000 which is configured in the pom.xml

**Comment by aramrami** [comment]
No support for CSRFGuard test apps. Please contact me directlty.
Azzeddine RAMRAMI
azzeddine.ramrami(at)owasp.org
