### ISSUE TITLE
CSRF JavascriptServlet not handling window.open and window.location

### ISSUE THREAD

**Issue by mmedjahed** [aramrami/OWASP-CSRFGuard#78]
Hi,
Did you get a solution to this??

(https://github.com/esheri3/OWASP-CSRFGuard/issues/69)

**Comment by supriya2612** [comment]
I'm looking for a solution for this as well. The window.location is updated in several parts of our code and the token does not get inserted automatically here.

**Comment by eighteen18** [comment]
I have fixed like this inside the popup:
var token = "";
try {
	token = window.opener.getTokenFromPage();
}
where "getTokenFromPage" is a js function used to thake the main window token.

function getTokenFromPage(){
	var token = "";
	if(CSRFGUARD_TOKEN != null && CSRFGUARD_TOKEN != ""){
		token = CSRFGUARD_TOKEN;
	}
	if($("input[name='OWASP_CSRFTOKEN']").length >0 && $("input[name='OWASP_CSRFTOKEN']").val() != ""){
		token = $("input[name='OWASP_CSRFTOKEN']").val();
	}
	return token;
}
