### ISSUE TITLE
Handling links and forms in dynamically generated content

### ISSUE THREAD

**Issue by supriya2612** [aramrami/OWASP-CSRFGuard#79]
We have some content that is generated dynamically. either via scripts or ajax calls which added new links/forms to the dom. We have enabled protection for GET requests as well. 

But since the JavaScriptServlet runs only once on dom load, the new links/forms do not get the token. How can we resolve this?

**Comment by bwolin** [comment]
I have the same question. Is there a manual way to execute the script on the new content?
