### ISSUE TITLE
CsrfGuardFilter needs to be reworked to allow a filter to prevent it from executing

### ISSUE THREAD

**Issue by ccronemberger** [aramrami/OWASP-CSRFGuard#8]
In my project I wanted to be able to bypass CsrfGuardFilter when the request is coming from another application server, so my first idea was to extend the filter to do it, but unfortunately it is final, so it can't be extended.

**Comment by hsn10** [comment]
write standard servlet api filter and place it before csrfguard.

**Comment by ccronemberger** [comment]
That is good idea, but will require a change in CSRFGuard anyway. If it was not final I could extend it and implement this idea. 

In any case I have changed the title.

**Comment by aramrami** [comment]
When you use CSRFGuard in your application you change it, update it, etc.
