### ISSUE TITLE
String prototype override issues

### ISSUE THREAD

**Issue by Koeroesi86** [aramrami/OWASP-CSRFGuard#85]
In csrfguard.js there is a String.prototype.endsWith and String.prototype.startsWith which overrides the default functionality in browsers. The endsWith although carries a huge potential of failure as it tries to execute the string as a regex as follows:

`String.prototype.endsWith = function(suffix) {
	return this.match(suffix+"$") == suffix;
};`

This makes a lot of calls failing on this function, the closest fix would be (if even this prototype is needed):

`String.prototype.endsWith = function(suffix) {
	return this.substr(-suffix.length) === suffix;
};`

**Comment by briandipalma** [comment]
I guess using the polyfill from MDN is the safest approach

```javascript
if (!String.prototype.endsWith)
  String.prototype.endsWith = function(searchStr, Position) {
      // This works much better than >= because
      // it compensates for NaN:
      if (!(Position < this.length))
        Position = this.length;
      else
        Position |= 0; // round position
      return this.substr(Position - searchStr.length,
                         searchStr.length) === searchStr;
  };
```

?

**Comment by briandipalma** [comment]
Two examples where it can fail:

```javascript
value.endsWith(').*$');
value.endsWith(').)*$');
```

Which cause `SyntaxError: Invalid regular expression: unmatched parentheses` errors. You can test this in a browser console:

```javascript
"prefix).*$".match(").*$"+"$")
```

**Comment by seryckd-jda** [comment]
I had replaced the prototypes a while back for the same reasons. Since other people are having this issue I pushed the changes as PR.

**Comment by briandipalma** [comment]
Thanks @seryckd-jda !

**Comment by aramrami** [comment]
Please send a pull request to be merged later.
