### ISSUE TITLE
CSRF is not injecting token in html page on IE prior to IE9

### ISSUE THREAD

**Issue by murlihiware** [aramrami/OWASP-CSRFGuard#90]
Hello,

I have used csrf JavaScript DOM Manipulation strategy for injecting token in my application
when I am accessing my application web site in IE compatibility mode(Document mode below 9) CSRF 
token is not getting injected in form

After spending some time in surfing on net I found below cause
DOMContentLoaded event(to register event handler for dom manipulation) used by csrf is not supported in older version of IE(below IE9) 
Reference https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded

Could you please suggest possible workaround to fix this.

**Comment by chenerzhu** [comment]
You can try the following.I hope it will help you deal with the IE browser version.
//getBrowserType
function getBrowserType()  
{  
  var userAgent = navigator.userAgent; //get userAgent
  var isOpera = userAgent.indexOf("Opera") > -1; //is Opera   
  var isIE = userAgent.indexOf("compatible") > -1 && userAgent.indexOf("MSIE") > -1 && !isOpera; //is IE
  var isEdge = userAgent.indexOf("Windows NT 6.1; Trident/7.0;") > -1 && !isIE; //is IE Edge 
  var isFF = userAgent.indexOf("Firefox") > -1; //is Firefox
  var isSafari = userAgent.indexOf("Safari") > -1 && userAgent.indexOf("Chrome") == -1; //is Safari
  var isChrome = userAgent.indexOf("Chrome") > -1 && userAgent.indexOf("Safari") > -1; //is Chrome

  if (isIE)   
  {  
	   var reIE = new RegExp("MSIE (\\d+\\.\\d+);");  
	   reIE.test(userAgent);  
	   var fIEVersion = parseFloat(RegExp["$1"]);  
	   if(fIEVersion == 7)  
	   { return "IE7";}  
	   else if(fIEVersion == 8)  
	   { return "IE8";}  
	   else if(fIEVersion == 9)  
	   { return "IE9";}  
	   else if(fIEVersion == 10)  
	   { return "IE10";}  
	   else if(fIEVersion == 11)  
	   { return "IE11";}  
	   else  
	   { return "0"}//IE is too old
   }//isIE end  
	 
   if (isFF) {  return "FF";}  
   if (isOpera) {  return "Opera";}  
   if (isSafari) {  return "Safari";}  
   if (isChrome) { return "Chrome";}  
   if (isEdge) { return "Edge";}  
}
var browser=getBrowserType();
console.log("browser is :"+browser);
if(browser=="IE8"||browser=="IE7"||browser=="0"){  // <= IE8 use onreadystatechange
	document.onreadystatechange=function(){ 
		if (this.readyState == "complete"){
			injectTokens(token_name, token_value);
		} 
	};
}else{//> IE8 use DOMContentLoaded
	addEvent(window,'DOMContentLoaded', function() {
		injectTokens(token_name, token_value);
	}); 
}

**Comment by murlihiware** [comment]
Thanks will try this.
