### ISSUE TITLE
New Release of OWASP-CSRFGuard

### ISSUE THREAD

**Issue by sappo** [aramrami/OWASP-CSRFGuard#95]
Hi,
is there a possibility to get a new release of the OWAS-CSRFGuard. The last release is 3 years old.

//Kevin

**Comment by bronogard** [comment]
@aramrami are you planning to release a new version soon? I hope so. thx

**Comment by aramrami** [comment]
Hi,

Not at this time.
Do you have any enhancement proposal to improve the project or any features?
Regards,
Azzeddine

**Comment by aramrami** [comment]
Not at this time.
Do you have any enhancement proposal to improve the project or any features?
Regards,
Azzeddine

**Comment by bronogard** [comment]
@aramrami thanks for the quick response.
I personally was hoping for a **minor** or at least a **patch** release.
I ran into a problem that was already fixed back in _October 2015_ - see: https://github.com/aramrami/OWASP-CSRFGuard/issues/27
Unfortunately, the currently release https://mvnrepository.com/artifact/org.owasp/csrfguard/3.1.0 from _November 2015_ does not contain it.
